# ----------- stage 1 ------------

FROM node:22 AS backend

WORKDIR /app

COPY package*.json ./

RUN npm install 

COPY . .


# ----------- stage 2 ------------

FROM node:22-slim

WORKDIR /app

COPY --from=backend /app .

EXPOSE 5000

CMD [ "node","index.js" ]