apiVersion: v1
kind: Secret 
metadata:
  name: mysql-secrets 
data:
  MYSQL_ROOT_PASSWORD: YWdkdHl1aW1uYg==      # Base64 encoded password for MySQL root user
                                               # Use: echo -n "yourPasswordHere" | base64
                                                # Stored securely so it's not visible in plain text

--- 

# mysql deployment 

apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mysql-deployment 
spec:
  selector: 
    matchLabels:
      app: mysql-pod 
  template: 
    metadata:
      labels:
        app: mysql-pod 
    spec: 
      containers:
        - name: mysql-container 
          image: mysql:8.0 
          env:
            - name: MYSQL_ROOT_PASSWORD 
              valueFrom: 
                secretKeyRef:
                  name: mysql-secrets           # Refers to the Secret object created above
                  key: MYSQL_ROOT_PASSWORD      # Refers to the specific key inside the Secret
                                               # This ensures MySQL container gets root password securely
            - name: MYSQL_DATABASE
              value: Students    # Not a secret, just the database name
