apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  namespace: todo-app
data:
  VITE_BACKEND_URL: aHR0cDovLzE5Mi4xNjguNDkuMjozMjY4NS9hcGk=
  MONGO_URL: bW9uZ29kYjovL2RhdGFiYXNlLXNlcnZpY2U6MjcwMTcvdG9kb3M=
