apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mongodb-deployment
spec:
 
  selector:
    matchLabels:
      app: mongodb-pod            # must match with pod name 
 
  template:
    metadata:
      labels:
        app: mongodb-pod          

    spec:
      containers:
        - name: mongodb-container 
          image: mongo:latest

        
--- 

# ---------------------Service for mongo deployment------------------------- 

apiVersion: v1 
kind: Service 
metadata:
  name: mongodb-service
spec: 

  selector:
    app: mongodb-pod                 # match with monodb pod name
  
  ports: 
  - protocol: TCP
    port: 27017 
    targetPort: 27017 
  type: NodePort                    # this is necessory for minikube service

