apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: website2-deployment 
spec: 
  selector:
    matchLabels:
      app: website2-pod 
  template:
    metadata:
      labels:
        app: website2-pod 
    spec:
      containers:
        - name: website2 
          image: shivamfullstack111/react-app-test:v6 
          ports:
            - containerPort: 5173

--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: website2-service 
spec:
  selector:
    app: website2-pod      # must match with pod labels 
  ports:
    - port: 5173 
      targetPort: 5173 
      protocol: TCP
  type: ClusterIP             # this type only work within the cluster 