# ----------------stage 1 (builder stage)---------------------------------------------------------------


# Small base image (Alpine Linux) for build
FROM node:22-alpine AS my-backend                                  

# Workdir set to /app inside container
WORKDIR /app                                                       

# Copy only package.json + package-lock.json first
COPY package*.json ./                                              

# Install dependencies
RUN npm install                                                    

# Copy rest of the app (source code, index.js etc.)
COPY . .                                                           



 # ------------------stage 2 (final stage)------------------------------------------------------------------------------------


# Slim base image (lighter than full node)
FROM node:22-slim                                                  

# Workdir again set to /app
WORKDIR /app                                                       

# Copy compiled/installed app from stage 1
COPY --from=my-backend /app .                                      

# Container exposes port 8000 (for backend API)
EXPOSE 8000                                                        

# Start backend server
CMD [ "node", "index.js" ]                                         
