apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deployment 
spec: 
  selector:
    matchLabels:
      app: nginx-pod 
  template:
    metadata:
      labels:
        app: nginx-pod 
        name: nginx-pod
    spec:   
      containers: 
        - name: nginx-container 
          image: nginx 
          ports:  
            - containerPort: 80 
          resources:                        # Mandatory for horizontal scaling 
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

--- 

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-pod
  ports:
  - port: 80
    targetPort: 80


# -------------------------------------BASIC COMMANDS ------------------------------------

# kubectl apply -f hpa.yaml                                             # Apply HPA manifest file and create HPA
# kubectl get hpa                                                       # Get list of all HPA resources
# kubectl describe hpa <hpa-name>                                       # Show detailed info of HPA (scaling rules, metrics, events)
# kubectl get hpa -w                                                    # Watch HPA in real-time (see replicas changing live)
# kubectl scale deployment nginx-deployment --replicas=5                     # Manually scale deployment (for testing)
# kubectl delete hpa <hpa-name>                                         # Delete HPA resource
